//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SampleParameters {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SampleParameters() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Test.SampleParameters", typeof(SampleParameters).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Your API Key].
        /// </summary>
        internal static string APIKey {
            get {
                return ResourceManager.GetString("APIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Your API Secret].
        /// </summary>
        internal static string APISecret {
            get {
                return ResourceManager.GetString("APISecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost:89/callback/.
        /// </summary>
        internal static string CallbackUrl {
            get {
                return ResourceManager.GetString("CallbackUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost:89/signing/.
        /// </summary>
        internal static string EmbeddedSigningUrl {
            get {
                return ResourceManager.GetString("EmbeddedSigningUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to some value.
        /// </summary>
        internal static string FormFillerSampleFieldValue {
            get {
                return ResourceManager.GetString("FormFillerSampleFieldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to peter.green@sample.com.
        /// </summary>
        internal static string Invitee1_Email {
            get {
                return ResourceManager.GetString("Invitee1_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peter.
        /// </summary>
        internal static string Invitee1_FirstName {
            get {
                return ResourceManager.GetString("Invitee1_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string Invitee1_LastName {
            get {
                return ResourceManager.GetString("Invitee1_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64.
        /// </summary>
        internal static string Invitee1_MobileCountry {
            get {
                return ResourceManager.GetString("Invitee1_MobileCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 021012345.
        /// </summary>
        internal static string Invitee1_MobileNumber {
            get {
                return ResourceManager.GetString("Invitee1_MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to peter.green@sample.com.
        /// </summary>
        internal static string Invitee2_Email {
            get {
                return ResourceManager.GetString("Invitee2_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peter.
        /// </summary>
        internal static string Invitee2_FirstName {
            get {
                return ResourceManager.GetString("Invitee2_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string Invitee2_LastName {
            get {
                return ResourceManager.GetString("Invitee2_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to some value.
        /// </summary>
        internal static string OAuth2State {
            get {
                return ResourceManager.GetString("OAuth2State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AuthenticateCode].
        /// </summary>
        internal static string Partner_TypeA_AuthenticateCode {
            get {
                return ResourceManager.GetString("Partner_TypeA_AuthenticateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [MembershipCode].
        /// </summary>
        internal static string Partner_TypeA_Code {
            get {
                return ResourceManager.GetString("Partner_TypeA_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to peter.green@sample.com.
        /// </summary>
        internal static string Partner_TypeA_User1_Email {
            get {
                return ResourceManager.GetString("Partner_TypeA_User1_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peter.
        /// </summary>
        internal static string Partner_TypeA_User1_FirstName {
            get {
                return ResourceManager.GetString("Partner_TypeA_User1_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string Partner_TypeA_User1_LastName {
            get {
                return ResourceManager.GetString("Partner_TypeA_User1_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alice.grey@sample.com.
        /// </summary>
        internal static string Partner_TypeB_Admin1_Email {
            get {
                return ResourceManager.GetString("Partner_TypeB_Admin1_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alice.
        /// </summary>
        internal static string Partner_TypeB_Admin1_FirstName {
            get {
                return ResourceManager.GetString("Partner_TypeB_Admin1_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grey.
        /// </summary>
        internal static string Partner_TypeB_Admin1_LastName {
            get {
                return ResourceManager.GetString("Partner_TypeB_Admin1_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to peter.green@sample.com.
        /// </summary>
        internal static string Partner_TypeB_User1_Email {
            get {
                return ResourceManager.GetString("Partner_TypeB_User1_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peter.
        /// </summary>
        internal static string Partner_TypeB_User1_FirstName {
            get {
                return ResourceManager.GetString("Partner_TypeB_User1_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string Partner_TypeB_User1_LastName {
            get {
                return ResourceManager.GetString("Partner_TypeB_User1_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost:89/callback/.
        /// </summary>
        internal static string PartnerAPICallback {
            get {
                return ResourceManager.GetString("PartnerAPICallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Your API Key].
        /// </summary>
        internal static string PartnerAPIKey {
            get {
                return ResourceManager.GetString("PartnerAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Your API Secret].
        /// </summary>
        internal static string PartnerAPISecret {
            get {
                return ResourceManager.GetString("PartnerAPISecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Path to attachment file].
        /// </summary>
        internal static string Path2AttachmentFile {
            get {
                return ResourceManager.GetString("Path2AttachmentFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Path to SmartTag document].
        /// </summary>
        internal static string Path2SmartTagDocument {
            get {
                return ResourceManager.GetString("Path2SmartTagDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.securedsigning.com/web.
        /// </summary>
        internal static string SecuredSigningServiceBase {
            get {
                return ResourceManager.GetString("SecuredSigningServiceBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v1.4.
        /// </summary>
        internal static string SecuredSigningServiceVersion {
            get {
                return ResourceManager.GetString("SecuredSigningServiceVersion", resourceCulture);
            }
        }
    }
}
